'use strict';

const messages = require('./messages.json');

const ACL_BACKEND_PREFIX     = 'sentry_acl';
const ACL_ROLE_ADMINISTRATOR = 'administrator';
const ACL_ACTION_VIEW        = 'view';
const ACL_ACTION_POST        = 'post';

const USER_ID_HEADER = 'x-remote-user';

const TOKEN_STATUS_REVOKED = 'revoked';
const TOKEN_STATUS_VALID   = 'valid';
const TOKEN_DURATION       = 7;
const TOKEN_DURATION_UNIT  = 'days';

const COLLECTION_TOKENS = 'tokens';
const COLLECTION_USERS  = 'users';

module.exports = {
  UNEXPECTED_NUM_DOCS: messages.ERRORS.UNEXPECTED_NUM_DOCS,
  USER_NOT_TOKEN_OWNER: messages.ERRORS.USER_NOT_TOKEN_OWNER,
  WEB_TOKEN_CREATION_MSG: messages.WEB_TOKEN.CREATION_MSG,
  WEB_TOKEN_REVOCATION_MSG: messages.WEB_TOKEN.REVOCATION_MSG,
  ACL_BACKEND_PREFIX,
  ACL_ROLE_ADMINISTRATOR,
  ACL_ACTION_VIEW,
  ACL_ACTION_POST,
  USER_ID_HEADER,
  TOKEN_STATUS_REVOKED,
  TOKEN_STATUS_VALID,
  TOKEN_DURATION,
  TOKEN_DURATION_UNIT,
  COLLECTION_TOKENS,
  COLLECTION_USERS,
};
